# Generated by Django 4.0.5 on 2022-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=40, null=True, verbose_name='Комментарий к заказу'),
        ),
    ]
