# Generated by Django 4.0.5 on 2022-10-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_order_delivered_order_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('EL', 'Electronic'), ('CS', 'Cash')], default='CS', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
