# Generated by Django 4.0.5 on 2022-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_called_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=40, verbose_name='Комментарий к заказу'),
        ),
    ]
