# Generated by Django 4.0.5 on 2022-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_order_latitude_order_longitude_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True, verbose_name='долгота'),
        ),
    ]
