# Generated by Django 4.0.5 on 2022-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_address_alter_order_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('EL', 'Electronic'), ('CS', 'Cash')], max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
