# Generated by Django 4.0.5 on 2022-11-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_rename_payment_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='called',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='registered',
            new_name='registered_at',
        ),
    ]
